# Generated by Django 4.2.11 on 2024-04-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="facebook",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="facebook"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="instagram",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="instagram"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="linkedin"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="x",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="x"
            ),
        ),
    ]
