# Generated by Django 4.2.11 on 2024-06-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_work_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="url2",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="URL2"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="url",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="URL"
            ),
        ),
    ]
